### ISSUE TITLE
还在维护吗

### ISSUE THREAD

**Issue by vaseala** [o2team/wxapp-component-base#1]
目前还在维护吗？我感觉该项目的实现思路不错，可以考虑搭配一款构建工具和一些约定的项目结构或规范

**Comment by Secbone** [comment]
@atmjs 这套方案目前京东小程序还在使用，不过比开放的这部分要复杂一些，也就是说还是有在维护的。至于配套的构建工具之类的，因为我们感觉目前的小程序框架还处于很不稳定的阶段，所以并没有做过多的整合，在后期小程序本身趋向成熟稳定以后，会进一步的跟进，也希望你能持续关注我们的动态。感谢！ 😄

**Comment by atmjs** [comment]
@Secbone  能把内部用的开源个beta版本不？

**Comment by atmjs** [comment]
https://github.com/cantonjs/wxapp-boilerplate 目前根据这个项目的模板修改了修改 然后内部调用的你们封装的page和component 感觉有点不伦不类

**Comment by jessjava** [comment]
您好，page.js 至今有新的变化吗？

**Comment by Secbone** [comment]
@jessjava @atmjs  这套方案暂时不维护了，替代是新的开发方案 [Taro](https://github.com/NervJS/taro)，感谢支持~ 😄

**Comment by jessjava** [comment]
Taro 有咩有解决页面间通信？

**Comment by Secbone** [comment]
@jessjava  Taro 支持 Redux 方式进行数据管理，所以也就解决了页面间通信的问题，当然也有提供其他途径实现页面通信，详情可以查看 Taro 的文档哈~
